# Generated by Django 2.2.5 on 2019-09-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('date', models.IntegerField(primary_key=True, serialize=False)),
                ('progressreport', models.TextField(db_column='progressReport')),
                ('profchange', models.IntegerField(db_column='profChange')),
                ('coopchange', models.IntegerField(db_column='coopChange')),
            ],
            options={
                'db_table': 'Session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('idstudent', models.AutoField(db_column='idStudent', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('absences', models.IntegerField()),
                ('profscore', models.IntegerField(db_column='profScore')),
                ('coopscore', models.IntegerField(db_column='coopScore')),
                ('parentemail', models.CharField(blank=True, db_column='parentEmail', max_length=45, null=True)),
                ('teacher', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('idtutor', models.AutoField(db_column='idTutor', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('admin', models.IntegerField()),
            ],
            options={
                'db_table': 'Tutor',
                'managed': False,
            },
        ),
    ]
