# Generated by Django 2.2.5 on 2019-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('idpair', models.AutoField(db_column='idPair', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Pair',
                'managed': False,
            },
        ),
    ]
